---

- hosts: iloservers

  tasks:
  - name: get ilo fw version
    shell: ilorest list Oem/Hpe/Firmware/Current/VersionString --selector=Manager.
    register: ilo
    become: yes

  - debug: var=ilo.stdout_lines