---

- hosts: ubuntuservers, debianservers

  tasks:
  - name: install restful interface tool from github
    yum:
      name: https://github.com/HewlettPackard/python-redfish-utility/releases/download/v3.0.1/ilorest-3.0.1-6_amd64.deb
      state: present
      validate_certs: False
    become: yes
